"""Tests for harness_probe.verify and the P0-2 verify CLI."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

from harness_probe.verify import (
    VerifyCheck,
    VerifyReport,
    aggregate_reports_to_json,
    aggregate_reports_to_markdown,
    report_to_json,
    report_to_markdown,
    verify_task,
)

REPO_ROOT = Path(__file__).resolve().parent.parent


def _make_task(
    tmp_path: Path,
    *,
    graph_delta: str = "none",
    human_gates: list[dict[str, Any]] | None = None,
    test_strategy: str = "not_applicable",
    slug: str = "test_verify",
    create_test_stub: bool = False,
) -> Path:
    gates = human_gates or [
        {"gate_id": "HG-TASK-DRAFT", "status": "approved", "blocks_hats": ["30"], "description": "draft"},
        {"gate_id": "HG-AUDIT-R1", "status": "approved", "blocks_hats": ["30"], "description": "R1"},
    ]
    frontmatter = f"""---
id: test-task-v1
title: Test Task
status: draft
module_id: VERIFY
graph_delta: {graph_delta}
test_strategy: {test_strategy}
freeze_id: v0.10.0
human_gates:
"""
    for g in gates:
        frontmatter += f"  - gate_id: {g['gate_id']}\n"
        frontmatter += f"    status: {g['status']}\n"
        frontmatter += f"    blocks_hats: {g['blocks_hats']}\n"
        frontmatter += f"    description: {g['description']}\n"
    frontmatter += "---\n\n# Test Task\n\n## 背景\n\nTest.\n\n### 人工闸\n\n"
    frontmatter += "| human_gate_id | status | blocks_hats | 说明 |\n"
    frontmatter += "| --- | --- | --- | --- |\n"
    for g in gates:
        hats = ", ".join(str(h) for h in g["blocks_hats"])
        frontmatter += f"| {g['gate_id']} | {g['status']} | {hats} | {g['description']} |\n"
    frontmatter += "\n## 验收\n\n- [ ] item\n"
    p = tmp_path / f"task_{slug}_v1.md"
    p.write_text(frontmatter, encoding="utf-8")

    if create_test_stub:
        tests_dir = tmp_path / "tests"
        tests_dir.mkdir(exist_ok=True)
        (tests_dir / "__init__.py").write_text("", encoding="utf-8")
        stub = tests_dir / f"test_{slug}.py"
        stub.write_text(
            '"""Stub test generated by test_verify.py."""\n\n'
            "def test_stub():\n"
            "    assert True\n",
            encoding="utf-8",
        )
    return p


class TestVerifyModels:
    def test_verify_report_serializes(self) -> None:
        check = VerifyCheck(name="x", passed=True, message="ok", duration_ms=1)
        report = VerifyReport(
            task_path="task.md",
            passed=True,
            blockers=[],
            checks=[check],
            summary="all good",
        )
        data = json.loads(report_to_json(report))
        assert data["task_path"] == "task.md"
        assert data["checks"][0]["name"] == "x"

    def test_report_to_markdown(self) -> None:
        check = VerifyCheck(name="x", passed=False, message="bad\nline", duration_ms=2)
        report = VerifyReport(
            task_path="task.md",
            passed=False,
            blockers=["x failed"],
            checks=[check],
            summary="1/1 passed",
        )
        md = report_to_markdown(report)
        assert "FAIL" in md
        assert "x" in md
        assert "bad line" in md
        assert "x failed" in md
        assert "|" in md

    def test_aggregate_reports(self) -> None:
        r1 = VerifyReport(
            task_path="a.md", passed=True, blockers=[], checks=[], summary="ok"
        )
        r2 = VerifyReport(
            task_path="b.md", passed=False, blockers=["x"], checks=[], summary="fail"
        )
        payload = json.loads(aggregate_reports_to_json([r1, r2]))
        assert len(payload) == 2
        assert payload[1]["passed"] is False
        md = aggregate_reports_to_markdown([r1, r2])
        assert "1/2 tasks passed" in md
        assert "b.md" in md


class TestVerifyTask:
    def test_valid_task_without_external_checks(self, tmp_path: Path) -> None:
        p = _make_task(tmp_path, graph_delta="none")
        report = verify_task(p, run_external_checks=False)
        assert report.passed is True
        assert not report.blockers
        assert any(c.name == "human_gates" and c.passed for c in report.checks)
        assert any(c.name == "graph_delta" and c.passed for c in report.checks)

    def test_missing_graph_delta(self, tmp_path: Path) -> None:
        p = _make_task(tmp_path, graph_delta="missing.graph.yaml")
        report = verify_task(p, run_external_checks=False)
        assert report.passed is False
        assert any("graph_delta" in b for b in report.blockers)

    def test_human_gate_blocks_30(self, tmp_path: Path) -> None:
        p = _make_task(
            tmp_path,
            graph_delta="none",
            human_gates=[
                {
                    "gate_id": "HG-AUDIT-R1",
                    "status": "pending",
                    "blocks_hats": ["30"],
                    "description": "R1 pending",
                }
            ],
        )
        report = verify_task(p, run_external_checks=False)
        assert report.passed is False
        assert any(c.name == "human_gates" and not c.passed for c in report.checks)
        assert any("HG-AUDIT-R1" in b for b in report.blockers)

    def test_strict_completed_is_illegal(self, tmp_path: Path) -> None:
        p = _make_task(
            tmp_path,
            graph_delta="none",
            human_gates=[
                {
                    "gate_id": "HG-AUDIT-R1",
                    "status": "completed",
                    "blocks_hats": ["30"],
                    "description": "R1",
                }
            ],
        )
        report = verify_task(p, strict=True, run_external_checks=False)
        assert report.passed is False
        messages = [c.message for c in report.checks if c.name == "human_gates"]
        assert any("completed" in m for m in messages)

    def test_required_test_strategy_missing(self, tmp_path: Path) -> None:
        p = _make_task(
            tmp_path,
            graph_delta="none",
            test_strategy="required",
        )
        # 让任务单文件名无法映射到任何测试文件，从而确保 required 失败
        content = p.read_text()
        p.unlink()
        p = p.with_name("task_no_such_feature_v99.md")
        p.write_text(content)
        report = verify_task(p, run_external_checks=False)
        assert report.passed is False
        assert any(c.name == "test_strategy" and not c.passed for c in report.checks)

    def test_required_test_strategy_found(self, tmp_path: Path) -> None:
        # There is a tests/test_verify.py file; task slug should map to it.
        p = _make_task(
            tmp_path,
            graph_delta="none",
            test_strategy="required",
        )
        # Rename the file to match the heuristic: test_verify*.py
        content = p.read_text()
        p.unlink()
        p = p.with_name("task_verify_v1.md")
        p.write_text(content)
        report = verify_task(p, run_external_checks=False)
        assert report.passed is True
        assert any(c.name == "test_strategy" and c.passed for c in report.checks)

    def test_external_checks_injected(self, tmp_path: Path) -> None:
        p = _make_task(
            tmp_path,
            graph_delta="none",
            slug="verify_injected",
            create_test_stub=True,
        )

        def fake_runner(cmd, **kwargs):
            class _Result:
                returncode = 0
                stdout = "ok"
                stderr = ""

            return _Result()

        report = verify_task(p, run_external_checks=True, _subprocess_runner=fake_runner)
        assert report.passed is True
        names = {c.name for c in report.checks}
        assert {"human_gates", "graph_delta", "test_strategy", "pytest", "ruff", "mypy"} <= names
        pytest_check = [c for c in report.checks if c.name == "pytest"][0]
        assert "test_" in pytest_check.message
        assert "pytest" in pytest_check.message

    def test_external_checks_injected_failure(self, tmp_path: Path) -> None:
        p = _make_task(tmp_path, graph_delta="none")

        def fake_runner(cmd, **kwargs):
            class _Result:
                returncode = 1
                stdout = ""
                stderr = "boom"
            return _Result()

        report = verify_task(p, run_external_checks=True, _subprocess_runner=fake_runner)
        assert report.passed is False
        assert any(c.name == "pytest" and not c.passed for c in report.checks)

    def test_task_file_not_found(self) -> None:
        report = verify_task("/no/such/task.md", run_external_checks=False)
        assert report.passed is False
        assert report.blockers[0].startswith("task file not found")


class TestVerifyCLI:
    def test_cli_verify_task_markdown(self, tmp_path: Path) -> None:
        p = _make_task(
            tmp_path,
            graph_delta="none",
            slug="verify_cli_markdown",
            create_test_stub=True,
        )
        out = subprocess.run(
            ["python", "-m", "harness_probe.cli", "verify", "--task", str(p), "--format", "markdown"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=60,
        )
        assert out.returncode == 0
        assert "PASSED" in out.stdout or "OK" in out.stdout

    def test_cli_verify_task_json(self, tmp_path: Path) -> None:
        p = _make_task(
            tmp_path,
            graph_delta="none",
            slug="verify_cli_json",
            create_test_stub=True,
        )
        out = subprocess.run(
            ["python", "-m", "harness_probe.cli", "verify", "--task", str(p), "--format", "json"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=60,
        )
        assert out.returncode == 0
        data = json.loads(out.stdout)
        assert data["passed"] is True

    def test_cli_verify_ci_returns_nonzero_on_failure(self, tmp_path: Path) -> None:
        p = _make_task(
            tmp_path,
            graph_delta="missing.graph.yaml",
            slug="verify_cli_ci",
            create_test_stub=True,
        )
        out = subprocess.run(
            ["python", "-m", "harness_probe.cli", "verify", "--task", str(p), "--ci"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=60,
        )
        assert out.returncode == 1
        assert "FAIL" in out.stdout or "graph_delta" in out.stdout

    def test_cli_verify_dir_batch(self, tmp_path: Path) -> None:
        _make_task(
            tmp_path,
            graph_delta="none",
            slug="verify_cli_dir_a",
            create_test_stub=True,
        )
        _make_task(
            tmp_path,
            graph_delta="none",
            slug="verify_cli_dir_b",
            create_test_stub=True,
            human_gates=[
                {
                    "gate_id": "HG-AUDIT-R1",
                    "status": "pending",
                    "blocks_hats": ["30"],
                    "description": "R1 pending",
                }
            ],
        )
        out = subprocess.run(
            ["python", "-m", "harness_probe.cli", "verify", "--dir", str(tmp_path), "--format", "json"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=120,
        )
        assert out.returncode == 1
        data = json.loads(out.stdout)
        assert len(data) == 2
        assert any(not r["passed"] for r in data)
        assert any(r["passed"] for r in data)

    def test_cli_verify_dir_empty(self, tmp_path: Path) -> None:
        out = subprocess.run(
            ["python", "-m", "harness_probe.cli", "verify", "--dir", str(tmp_path)],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=60,
        )
        assert out.returncode == 2

    def test_cli_pre_spawn_verify(self, tmp_path: Path) -> None:
        p = _make_task(
            tmp_path,
            graph_delta="none",
            slug="verify_cli_pre_spawn",
            create_test_stub=True,
        )
        out = subprocess.run(
            ["python", "-m", "harness_probe.cli", "verify", "--task", str(p), "--pre-spawn"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=60,
        )
        assert out.returncode == 0
        assert "PRE_SPAWN_VERIFY pass" in out.stdout
